# Generated by Django 2.0.7 on 2018-07-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('description', models.TextField(verbose_name='Опис')),
                ('image', models.ImageField(upload_to='products/images', verbose_name='Зображення')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Зображення')),
                ('available', models.BooleanField(default=True, verbose_name='Зображення')),
                ('brand', models.ForeignKey(on_delete=None, to='app.Brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=None, to='app.Category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
            },
        ),
    ]
