# Generated by Django 2.0.7 on 2018-08-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180801_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Загальна ціна')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзини',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('item_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Загальна ціна')),
                ('product', models.ForeignKey(on_delete=None, to='app.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Елемент корзини',
                'verbose_name_plural': 'Елементи корзини',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='app.CartItem', verbose_name='Елементи корзини'),
        ),
    ]
