# Generated by Django 2.0.7 on 2018-08-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180802_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='app.CartItem', verbose_name='Елементи корзини'),
        ),
    ]
