# Generated by Django 2.0.7 on 2018-08-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180802_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='data',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Добавлений до обробки', 'Добавлений до обробки'), ('Виконується', 'Виконується'), ('Сплачено', 'Сплачено')], default='Добавлений до обробки', max_length=200, verbose_name='Статус замовлення'),
        ),
    ]
