# Generated by Django 2.0.7 on 2018-08-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180802_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='app.CartItem', verbose_name='Товари'),
        ),
    ]
